var placecity = {
    AllurisitharamaRaju: 
    {
        Paderu:{},
        Rampachodavaram:{},
        Ananthagiri:{},
        Arakuvalley:{},
        Chintapalli:{},
    },
    Anakapalli:
    {
        Elamanchali:{},
        Narsipatnam:{},
        Bowluvada:{},
        Chodavaram:{},
        Mulakuddu:{},
    },
    Ananthapuram:
    {
        Beluguppa:{},
        Bommanahal:{},
        Brahmasamudram:{},
        Gummagatta:{},
        Kalyandurg:{},
    },
    Bapatla:
    {
        Chirala:{},
        Bapatla:{},
        Addanki:{},
        Reppale:{},
        Parchur:{},
    },
    Chittoor:
    {
        Chittoor:{},
        Nagari:{},
        Punganur:{},
        Palamaner:{},
        Kuppam:{},
    },
    DRBRAmbedhkarKonaseema:
    {
        Ravulapalem:{},
        Amalapuram:{},
        Rayavaram:{},
        Ramachandrapuram:{},
        Kothapeta:{},
    },
    EastGodavari:
    {
        Anaparthi:{},
        Bikkavolu:{},
        Devarapalle:{},
        Gopavaram:{},
        Kadiam:{},
        Kovvur:{},
        Nidadavolu:{},
        RajamahendravaramRural:{},
        RajamahendravaramUrban:{},
        Rajanagaram:{},
        Tallapudi:{},
    },
    Eluru:
    {
       Bhimadolu:{},
       Buttayagudam:{},
       Chintalapudi:{},
       Denduluru:{},
       DwarakaTirumala:{},
       Eluru:{},
       Jangareddyguden:{},
       Kaikaluru:{},
       Kalidindi:{},
       Mudinepalli:{},
       Nidamarru:{},
       Nuzividu:{},
       Polavaram:{},
       Unguturu:{}, 
    },
    Guntur:
    {
        Chebrolu:{},
        Duggirala:{},
        GunturEast:{},
        GunturWest:{},
        Mangalagiri:{},
        Pedakakani:{},
        Phirangipuram:{},
        Ponnur:{},
        Prathipadu:{},
        Tadepalli:{},
        Tenali:{},
        Thulluru:{}
    },
    Kakinada:
    {
        Gollaprolu:{},
        KakinadaRural:{},
        KakinadaUrban:{},
        Karapa:{},
        Kirlampudi:{},
        Pedapudi:{},
        Pedapuram:{},
        Pithapuram:{},
        Prathipadu:{},
        Samalkota:{},
        Tuni:{},
        Thallarevu:{},
        Ukothapalli:{},
        Yeleswaram:{},
    },
    Krishna:
    {
        Avanigadda:{},
        Gannavaram:{},
        Ghantasala:{},
        Gudivada:{},
        Gudlavalleru:{},
        Guduru:{},
        Koduru:{},
        Machilipatanam:{},
        Pamaru:{},
        Penamuluru:{},
        Unguturu:{},
        vuyyuru:{},
    },
    Kurnool:
    {
        Adoni:{},
        CBelagal:{},
        Devanakonda:{},
        Guduru:{},
        Kallur:{},
        Kodumur:{},
        Krishnagiri:{},
        KurnoolRural:{},
        KurnoolUrban:{},
        Mantralayam:{},
        Nandavaram:{},
        Orvakal:{},
        Pattikonda:{},
        Tuggali:{},
        Yemmiganur:{},
    },
    Nandyal:
    {
        Allagadda:{},
        Atmakur:{},
        Banaganapalli:{},
        Bethamcherla:{},
        Chagalamarri:{},
        Dhone:{},
        Koilakuntla:{},
        Kolimigundla:{},
        kothapalle:{},
        Mahanandhi:{},
        Nandikotkur:{},
        Nandyal:{},
        Rudravaram:{},
        Srisailam:{},
        Uyyalavada:{},
    },
    NTR:
    {
        Ibrahimpatnam:{},
        jaggiaihpeta:{},
        Mylavaram:{},
        Nandigama:{},
        Tiruvuru:{},
        Vijayawadarural:{},
        VijayawadaCentral:{},
        VijayawadaEast:{},
        VijayawadaWest:{},
    },
    Palnadu:
    {
        Amaravathi:{},
        Atchampeta:{},
        Bellamkonda:{},
        Chilakaluripet:{},
        Dachepalli:{},
        Gurajala:{},
        Krosuru:{},
        Machavaram:{},
        Macherla:{},
        Nadendla:{},
        Narasaraopet:{},
        Nuzendla:{},
        Piduguralla:{},
        Rentachintala:{},
        Sattenpalli:{},
        Vinukonda:{},
        Veldurthy:{},
    },
    ParvathipuramManyam:
    {
        Bhamini:{},
        Garugubilli:{},
        Gommalakshmipuram:{},
        Kurupam:{},
        Palakonda:{},
        Parvathipuram:{},
        Salur:{},
        Seethampeta:{},
        Veeraghattam:{},
    },
    Prakasam:
    {
        Darsi:{},
        Giddalur:{},
        Kanigiri:{},
        Komarolu:{},
        Markapuram:{},
        Ongole:{},
        Pamur:{},
        Ponnaluru:{},
        Racherla:{},
        Singarayakonda:{},
        Tangutur:{},
        Tallur:{},
        Veligandla:{},
    },
    SripottiSriRamuluNellore:
    {
        Atmakur:{},
        Buchireddipalem:{},
        Dagadarthi:{},
        Kaligiri:{},
        Kandukuru:{},
        Kavali:{},
        Kovur:{},
        NelloreRural:{},
        NelloreUrban:{},
        Sangam:{},
        Seetharampuram:{},
        Udayagiri:{},
        Ulavapadu:{},
        Varikuntapadu:{},
        Venkatachalam:{},
    },
    SriSathyaSai:
    {
        Amarapuram:{},
        Bathalapalli:{},
        Dharamavaram :{},
        Gorantla:{},
        Hindupur:{},
        Kadiri:{},
        Lepakshi:{},
        Mudigubba:{},
        Nallacheruvu:{},
        Obuladevaracheruvu:{},
        Penukonda:{},
        Puttaparthy:{},
    },
    Srikakulam:
    {
        Amadalavalasa:{},
        Etcherla:{},
        Hiramandalam:{},
        Gara:{},
        Ichchapuram:{},
        Jalumuru:{},
        Kanchili:{},
        Kaviti:{},
        Kotabommali:{},
        Mandasa:{},
        Meliaputti:{},
        Nandigam:{},
        Narasannapeta:{},
        Palasa:{},
        Pathapatnam:{},
        Polaki:{},
        Ranasthalam:{},
        Saravakota:{},
        Srikakulam:{},
        Tekkali:{},
    },
    Tirupathi:
    {
        Chandragiri:{},
        Gudur:{},
        Naidupet:{},
        Puttur:{},
        Ramachandrapuram:{},
        Renigunta:{},
        Sathyavedu:{},
        Srikalahasti:{},
        Sullurpeta:{},
        TirupathiRural:{},
        TirupathiUrban:{},
        Venkatagiri:{},
    },
    Visakhapatnam:
    {
        Anandapuram:{},
        Bheemunipatnam:{},
        Gajuwaka:{},
        Gopalapatnam:{},
        Pendurthi:{},
        Seethammadhara:{},
        VisakhapatnamRural:{},
    },
    Vizianagaram:
    {
        Bhogapuram:{},
        Bobbili:{},
        Chipurupalle:{},
        Gajapathinagaram:{},
        Garividi:{},
        Gurla:{},
        Kotthavalasa:{},
        Nellimarla:{},
        Rajam:{},
        Ramabhadrapuram:{},
        Srungavarapukota:{},
        Vangara:{},
        Vizianagaram:{},
    },
    WestGodavari:
    {
        Akividu:{},
        Attili:{},
        Bhimavaram:{},
        Ganapavaram:{},
        Mogalathur:{},
        Palacole:{},
        Penugonda:{},
        Tadepalligudem:{},
        Tanuku:{},
        Yelamanchili:{},
    },
    YSR:
    {
        BKodur:{},
        Badvel:{},
        Brahmamgarimattam:{},
        Chennur:{},
        Gopavaram:{},
        Jammalamadugu:{},
        Kadapa:{},
        Khajipeta:{},
        Mylavaram:{},
        Proddutur:{},
        Pulivendula:{},
        Simhadripuram:{},
        Vallur:{},
        Vempalli:{},
        Vontimitta:{},
        Yerraguntla:{},
    
    }

} 
window.onload = function()
{
const selectdistrict = document.getElementById('Place'),
      selectcity = document.getElementById('city'),
      selects = document.querySelectorAll('select')

      selectcity.disabled= true

      selects.forEach(select => {
        if(select.disabled == true)
        {
            select.style.cursor = "auto"
        }
        else{
            select.style.cursor = "pointer"
        }
      })

      for(let place in placecity)
      {
        console.log(place);
        selectdistrict.options[selectdistrict.options.length]=new Option(place,place)
      }

      selectdistrict.onchange = (e) => 
      {
        selectcity.disabled = false
        selects.forEach(select => {
            if(select.disabled == true)
            {
                select.style.cursor = "auto"
            }
            else{
                select.style.cursor = "pointer"
            }
          })
        selectcity.length = 1

        for(let city in placecity[e.target.value])
        {
            console.log(city);
            selectcity.options[selectcity.options.length]=new Option(city,city)
        }
      }
}